media:
  - name: images
    label: Images
    input: images
    output: /images
    rename: safe
    categories: [image]

content:
  - name: posts
    label: Posts
    type: collection
    path: _posts
    filename: "{year}-{month}-{day}-{title}.md"
    view:
      fields: [title, date, tags]
      primary: title
      sort: [date, title]
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: date
        label: Date
        type: date
        required: true
      - name: tags
        label: Tags
        type: string
        list: true
        description: Add tags such as 水软, 猴软, 科笛.
      - name: body
        label: Body
        type: rich-text
        options:
          format: markdown
          media: images
          path: images/posts
          rename: safe
          switcher: true

settings:
  content:
    merge: true
  commit:
    templates:
      create: "Create {path}"
      update: "Update {path}"
      delete: "Delete {path}"
      rename: "Rename {oldPath} to {newPath}"
